### ISSUE TITLE
 introduction notebook doesn't walk users through auth

### ISSUE THREAD

**Issue by fcollman** [seung-lab/AnnotationFrameworkClient#10]
the first cells of the notebook need to setup auth

**Comment by fcollman** [comment]
also if you don't have a .cloudvolume secrets directory

**Comment by ceesem** [comment]
Changes made in fc9e22f address some bugs in auth that should help make setting up auth easier and give more useful errors. The example notebook has been updated as well.

**Comment by ceesem** [comment]
Solved by #12
